# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/basys3-master.xdc

# Block Designs: bd/main/main.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main || ORIG_REF_NAME==main} -quiet] -quiet

# IP: bd/main/ip/main_c_counter_binary_0_0/main_c_counter_binary_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_c_counter_binary_0_0 || ORIG_REF_NAME==main_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xlslice_0_0/main_xlslice_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlslice_0_0 || ORIG_REF_NAME==main_xlslice_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xlconstant_0_0/main_xlconstant_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconstant_0_0 || ORIG_REF_NAME==main_xlconstant_0_0} -quiet] -quiet

# IP: bd/main/ip/main_xlconstant_1_0/main_xlconstant_1_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_xlconstant_1_0 || ORIG_REF_NAME==main_xlconstant_1_0} -quiet] -quiet

# IP: bd/main/ip/main_UC_0_0/main_UC_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==main_UC_0_0 || ORIG_REF_NAME==main_UC_0_0} -quiet] -quiet

# XDC: d:/228491/PUL/MGR/project_12/project_12.gen/sources_1/bd/main/main_ooc.xdc
