# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/228491/PUL/MGR/project_12/project_12.srcs/sources_1/bd/main/ip/main_c_counter_binary_0_0/main_c_counter_binary_0_0.xci
# IP: The module: 'main_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/228491/PUL/MGR/project_12/project_12.gen/sources_1/bd/main/ip/main_c_counter_binary_0_0/main_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/228491/PUL/MGR/project_12/project_12.srcs/sources_1/bd/main/ip/main_c_counter_binary_0_0/main_c_counter_binary_0_0.xci
# IP: The module: 'main_c_counter_binary_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/228491/PUL/MGR/project_12/project_12.gen/sources_1/bd/main/ip/main_c_counter_binary_0_0/main_c_counter_binary_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'main_c_counter_binary_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
